---
- name: Build container image
  hosts: localhost
  collections:
    - evgnomon.catamaran
  roles:
    - role: z_container
    - role: z_sshadd

- name: Add front
  hosts: localhost
  tasks:
    - name: Add front
      add_host:
        name: "{{ item }}"
        groups: front
        ansible_user: "root"
      with_items:
        - front-a-1.zygote.run
        - front-b-1.zygote.run

- name: Deploy pod
  hosts: front
  collections:
    - evgnomon.catamaran
  roles:
    - role: z_pod
      vars:
        public_port: 3000
