name: Yacht

on:
  push:
    branches:
      - '*'
  delete:
    branches:
      - '*'
      - '!main'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  yacht:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/evgnomon/barge:main
    steps:
    - uses: actions/checkout@v4
    - name: Run Playbook
      uses: evgnomon/yacht@main
      with:
        vault: ${{ secrets.VAULT_FILE }}
        vault_pass: ${{ secrets.VAULT_PASS }}
        container_network: ${{ job.container.network }}
        # github_token: ${{ secrets.GITHUB_TOKEN }}
